# config.yml

theme: jekyll-theme-minimal # Replace with your preferred Jekyll theme
title: Isobel Abell
description: PhD student, the University of Melbourne
# repository: iabell/yourrepository # Update with your GitHub username and repository name

# Build settings
markdown: kramdown
permalink: /:title/

# GitHub Pages settings
remote_theme: jekyll/minimal # Replace with the theme you want to use
plugins:
  - jekyll-feed

# Additional settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
